# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io

# [ docker-compose ]
services:
  noip:
    image: ghcr.io/noipcom/noip-duc:3.2.0
    container_name: noip
    user: root
    restart: always
    environment:
      - "NOIP_USERNAME=zrfisaac@gmail.com"
      - "NOIP_PASSWORD=ABcd!@34"
      - "NOIP_HOSTNAMES=zrfisaac.ddns.net"
    network_mode: "host"
