# [ zrfisaac ]

# [ about ]
# - author : Isaac Caires
# . - email : zrfisaac@gmail.com
# . - site : zrfisaac.github.io

# [ docker-compose ]
services:
  postgres14:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_DB: "debug"
      POSTGRES_PASSWORD: "ABcd!@34"
    volumes:
      - "./public:/public"
    ports:
      - "5432:5432"
    network_mode: "host"
